///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SignupModel {
/*
{
  "status": false,
  "resultCode": 500,
  "message": "Kimlik Numarası Kayıtlıdır",
  "token": null,
  "data": 404
}
*/

  bool status;
  int resultCode;
  String message;
  String token;
  int data;

  SignupModel({
    this.status,
    this.resultCode,
    this.message,
    this.token,
    this.data,
  });
  SignupModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    resultCode = json['resultCode']?.toInt();
    message = json['message']?.toString();
    token = json['token']?.toString();
    data = json['data']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['resultCode'] = resultCode;
    data['message'] = message;
    data['token'] = token;
    data['data'] = this.data;
    return data;
  }
}
